services:
  app:
    image: nextcloud:apache
    container_name: nextcloud-dev
    ports:
      - "8081:80"
    volumes:
      - nextcloud_data:/var/www/html
      - ./my-nextcloud-app:/var/www/html/custom_apps/my-nextcloud-app
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: nextcloud-redis
    restart: unless-stopped

  cron:
    image: nextcloud:apache
    container_name: nextcloud-cron
    depends_on:
      - app
    volumes:
      - nextcloud_data:/var/www/html
    entrypoint: ["/cron.sh"]
    restart: unless-stopped

volumes:
  nextcloud_data:
